### ISSUE TITLE
Wishlist of backwards incompatible things for a future Racket2.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket2-rfcs#33]
Following text was moved form https://github.com/racket/racket/wiki/Racket2

some entries below should be logged as separate issues

--
# A Wishlist of backwards incompatible things for a future Racket2.

**Note**: This is a wishlist. There's no guarantee any of these will be in a Racket2.

- [X] Remove `cond`'s default else-is-void clause and replace with a default else-is-error.
Done: #39

- [X] Change `match` to recognize clauses based on bindings instead of symbols, and make
  it treat `else` like `cond`. #40 Closed as duplicate of #23

- [X] Make every place where binding variables currently appear allow arbitrary match patterns (this requires some thought for handling what is currently things like `(define (f x) ..)`, so maybe we do this in a more limited way or change that way of defining functions to use a new keyword)
Done: #36

- [X] Building on the match allowance, also allow functions to be defined case-by-case, for example maybe using a notation like this (roughly allowed in all internal definition contexts where `:=` is the keyword that triggers this kind of parsing):

        (length '()) := 0
        (length (cons x y)) := (+ 1 (len y))

And, even better, have this turn into `define/contract` or maybe `provide/contract` if something like this is written:

        length : (-> list? exact-nonnegative-integer?)
        (length '()) := 0
        (length (cons x y)) := (+ 1 (len y))
Done: #41

- [X] More prefabs for basic values, especially ones like srclocs where it is useful to make cross phase
  movements easy.
Done: #42

- [X] Enable internal definitions everywhere.  (Note: this is tricky -- what's "everywhere"?
  Eg, can `define id` be followed by a definition(s) and then a value?  How about in the middle
  of an `if`?  Taken to an extreme, could definitions appear in an application form?)
#63 (possible dup of #46?)

- [X] change syntax-case to allow internal definitions (possibly by getting rid of the 'guard' section)
#64 

- [X] Enable the `define*` form (from `racket/package`) everywhere
Done: #46

- [X] Use keywords in more places, such as unifying `member`, `memv`, `memf`, etc. #65 

- [x] Some syntax that avoids the verbosity in the `keyword-apply` etc kind of functions in the common  case of passing keywords around. #66

- [X] Some solution to the "no-value" value, which could be such a blessed value, or it could be a way
  to say that some function accepts all the keywords as some other function.  (Possibly related to
  the above, of course.) #67

- [x] `struct` definition macro that allows
  - naming of the accessors/constructors/etc
  - ~~per-field `#:auto` values~~
  - ~~creating a constructor that takes all fields (when `#:auto` values should be something different)~~
  - ~~creating a constructor that makes `#:auto` fields optional keyword arguments~~
  - make `struct` have a function-like form that can specify auto values as optionals and/or keywords
  - maybe even allow several constructors with different argument "shapes"
  - more ideas from CL, like a `struct` keyword that actually use (tagged) lists for the values,
    similar to prefabs (and possibly redundant because of them)
  - like [sstruct2](https://github.com/jeapostrophe/exp/blob/master/sstruct2.rkt)

- [X] Have only either `struct` or `define-struct`. Not both. #68

- [X] Disallow mutation of `struct` bindings.  #69

- [X] Change `integer?` to mean `exact-integer?`.  #52

- [X] Get rid of the `arity-at-least` struct, and replace it with just an `arity` that abstracts over the whole arity thing -- always normalizing and includes keyword arity information.  Also, make it possible to always use a procedure where an arity is expected. #72

- [X] Reconsider printing and equality of mutable and immutable variants of data types (vectors,
  hash tables, strings, etc.). Also reconsider the coercion of mutable vectors to immutable
  vectors by `datum->syntax`. #73

- [X] Add CLOS-like defmethod (with multidispatch and :before, :after, :around) on Racket classes. #74

- [X] Add interactive breakpoint in DrRacket debug. One should have REPL at breakpoint #70

- [X] Have `with-output-to-string` and friends take a body, not a thunk. The current form is better named `call-with-output-to-string`, in the general pattern of `with-x` being syntax and `call-with-x` being a procedure. #54

- [X] Have `<`, `>` and others take 0 or more arguments (returning `#t` for the 0 and 1 argument cases). This would allow applying them to lists without fear, which would allow patterns like `(define (sorted? l) (apply < l))`  #53

- [X] Rename `racket/cmdline` to `racket/command-line`.  #56

- [X] Require that macro literals always be bound.  #55

- [X] Make Matthew's doc-define from ClojureWest keynote real #60

- [X] Consider having real identifiers for class/object members and use the module/namespace mechanisms to manage these references. Possibly in conjunction with a convention for names that are prefixed or included in others (so that we can have identifiers like `frame%:show` treated specially). Potentially makes method invocation faster and allows static detection of method-not-found errors. #61

- [X] Have `quasiquote` support `...` as well as `,@`. Among other things, this lets `match` patterns can be like `match` "templates" (output expressions) and be like `syntax-case` etc. #62

**Comment by jeapostrophe** [comment]
This should definitely be split up :)

**Comment by gus-massa** [comment]
Some of the items already discuses in https://github.com/racket/racket2-rfcs/issues/22 In particular:

* Drop more guarantees about new object allocations: ...

* Make `string`s immutable.

I think it's better to keep the discussion of both of them there in a single issue. (It can be split, but in my opinion they are interleaved and it's better to make a single thread about them.)

---

Some some should be merged in a single issue: 

* Remove `cond`'s default else-is-void clause and replace with a default else-is-error.

* Consider changing `cond` (and `match`) to use `#:else` instead of `else`.

---

Some are already implemented (IIRC):

* More prefabs for basic values, especially ones like `srclocs` where it is useful to make cross phase
movements easy.

But I think it's better to add even more things to the cross phase list (is that the current official name?). In particular I was surprised that `set`s are not cross phase. Most of this can be implemented in racket1. (Is racket1 the official name?)

---

Some can be added to racket1. In particular I think we can add this tomorrow:

* Have `<`, `>` and others take `0` or more arguments (returning `#t` for the `0` and `1` argument cases).

I don't have time to implement it now, but it looks straightforward. (And probably need some kind of discussion and approval, but it is a very good idea!)

**Comment by spdegabrielle** [comment]
split up named entries: 

- [X] Drop more guarantees about new object allocations: for example, allow `(append lst '())` to return `lst`,
  and the same for other list, string, bytes, vector functions (drop 0 items from the end of a list,
  `substring` and `regexp-replace` that don't change a string, etc). - @elibarzilay 3 Oct 2012  #37
- [X] include pattern matching forms in more binding positions (e.g. `define`, `let`/`for` clauses) - @samth 2 Oct 2012 #36

- [X] Generic programming by default: `map`, `fold`, and friends are generic and not specialized to lists. - @takikawa 3 Oct 2012 #35

**Comment by spdegabrielle** [comment]
- [X] Make strings immutable 
removed - covered by #22

**Comment by spdegabrielle** [comment]
Hi @gus-massa I’ve actiond a couple of your points, but not done all. I’ll break them up into separate issues so the can be discussed and actioned individually. 
(Leaving this as a big list makes it confusing, unmanagable and impossible to close.)

**Comment by gus-massa** [comment]
I completely agree. My separation was just a suggestion about how to split/merge some of the points in the wiki.

**Comment by spdegabrielle** [comment]
@gus-massa would you be willing to log some of the above points as separate issues, so we can close them off here?
Ideally I'd like to close this issue but giving all the distinct items above their own issue.
S.

**Comment by gus-massa** [comment]
Direct link to the parts I copied. Are you going to remove them from the top post? It will make finding the missing parts much easier

- [x] Change `integer?` to mean `exact-integer?`. #52 

- [x] Have `<`, `>` and others take `0` or more arguments (returning `#t` for the `0` and `1` argument cases). This would allow applying them to lists without fear, which would allow patterns like `(define (sorted? l) (apply < l))` #53 

- [x] Have `with-output-to-string` and friends take a body, not a thunk. The current form is better named `call-with-output-to-string`, in the general pattern of `with-x` being syntax and `call-with-x` being a procedure. #54 

- [x] Require that macro literals always be bound. #55 

- [x] Rename `racket/cmdline` to `racket/command-line` #56

**Comment by spdegabrielle** [comment]
Thank you @gus-massa 
I will remove from top post

**Comment by sorawee** [comment]
More "done" items

> * [x]  Remove `cond`'s default else-is-void clause and replace with a default else-is-error.

Done: #39

> * [x]  Change `match` to recognize clauses based on bindings instead of symbols, and make
>   it treat `else` like `cond`.

Done: #30 

> * [x]  Make every place where binding variables currently appear allow arbitrary match patterns (this requires some thought for handling what is currently things like `(define (f x) ..)`, so maybe we do this in a more limited way or change that way of defining functions to use a new keyword)

Done: #36

> * [x]  Building on the match allowance, also allow functions to be defined case-by-case, for example maybe using a notation like this (roughly allowed in all internal definition contexts where `:=` is the keyword that triggers this kind of parsing):

>   ```
>     (length '()) := 0
>     (length (cons x y)) := (+ 1 (len y))
>   ```
> 
> And, even better, have this turn into `define/contract` or maybe `provide/contract` if something like this is written:
> 
> ```
>     length : (-> list? exact-nonnegative-integer?)
>     (length '()) := 0
>     (length (cons x y)) := (+ 1 (len y))
> ```
> 

Done: #41

> * [x]  More prefabs for basic values, especially ones like srclocs where it is useful to make cross phase
>   movements easy.

Done: #42

> * [x]  Enable the `define*` form (from `racket/package`) everywhere

Done: #46

**Comment by spdegabrielle** [comment]
Thanks @gus-massa

**Comment by spdegabrielle** [comment]
All items have own issues. Closing 
@gus-massa @jeapostrophe @sorawee
